### ISSUE TITLE
TreeDiagram example produces unexpected results

### ISSUE THREAD

**Issue by FourierMourier** [MerrimanInd/drawpyo#39]
Hi! Thank you for your project - really cool and helpful! However, I found some problem with the newest version only - `drawpyo==0.2`, whilst `drawpyo==0.1.3` results as expected. Here's the code from the [README.md](https://github.com/MerrimanInd/drawpyo/blob/765f475ddd5b968105e6a5bfbffdf92891356972/README.md) regarding the `TreeDiagram` object

```python
import os
from os import path
from drawpyo.diagram_types import TreeDiagram
from drawpyo.diagram_types import NodeObject


def main():
    filepath = path.join(os.getcwd(), "example.drawio")
    tree = TreeDiagram(
        file_path=path.dirname(filepath),
        file_name=path.basename(filepath),
        direction="down",
        link_style="orthogonal",
    )

    # Top object
    grinders = NodeObject(tree=tree, value="Appliances for Grinding Coffee", base_style="rounded rectangle")

    # Main categories
    blade_grinders = NodeObject(tree=tree, value="Blade Grinders", parent=grinders)
    burr_grinders = NodeObject(tree=tree, value="Burr Grinders", parent=grinders)
    blunt_objects = NodeObject(tree=tree, value="Blunt Objects", parent=grinders)
    # Other
    elec_blade = NodeObject(tree=tree, value="Electric Blade Grinder", parent=blade_grinders)
    mnp = NodeObject(tree=tree, value="Mortar and Pestle", parent=blunt_objects)

    # Conical Burrs
    conical = NodeObject(tree=tree, value="Conical Burrs", parent=burr_grinders)
    elec_conical = NodeObject(tree=tree, value="Electric", parent=conical)
    manual_conical = NodeObject(tree=tree, value="Manual", parent=conical)

    tree.auto_layout()
    tree.write()


if __name__ == '__main__':
    main()

```

Which eventually results in something like this:
<img width="1257" alt="image" src="https://github.com/user-attachments/assets/50748362-237f-4aec-828e-18cc83766856">

The diagram is too wide (to be fully displayed here) and unstructured =/

Platform: Windows 11
Python version: 3.11.7

**Comment by MerrimanInd** [comment]
Hey @FourierMourier, as soon as I saw the preview text for your issue I knew what I broke. Definitely something I meant to address then forgot before I released it. I created `parent` attributes in the base drawpyo library so now the TreeDiagram library is reusing them. Should be able to get a fix out asap, thanks for the note!

**Comment by FourierMourier** [comment]
unfortunately, the issue is still there in the newest release too (0.2.1)

**Comment by MerrimanInd** [comment]
Yep sorry that was a breaking change in the API :(

Basically when someone else requested I support the list object type I needed to handle containers. In the Draw.io file structure they specifically call an owning container object the parent. So I co-opted that keyword for the base Object type and forgot to change it in TreeDiagram. I shifted everything in TreeDiagram to be tree_parent, tree_children, etc. Initially I thought about keeping with the tree theme and naming all the attributes tree stuff like trunk, branch, leaf, etc. It was cute but I thought it would be confusing.
